name: Ideas Workshop
favicon: null
layout_spectrum: 1
typography_spectrum: 0.25053
title: Advertising Agency and PR
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff6410'
    - '#96989a'
    - '#fefefe'
    - '#454344'
    - '#000000'
  brandStrength: 0.5
  lightness: 0.7624779108446091
  saturation: 0.6875
  rhythmicContrast: 1
purpose: []
